### ISSUE TITLE
USER STORY: User can change their password

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#10]
As a **user** I can **change my password** so that **I can keep my account secure**

## Acceptance Criteria
- Acceptance Criteria 1:
**Given**  that I am a registered user, logged into my account 
**When** I navigated the edit profile page
**Then** I have the option to change password

Acceptance Criteria 2
**Given** that I am logged into my account
**When** I click the change password link and submit my new password
**Then** my password is changed and I recive confirmation on screen

Acceptance Criteria 3
**Given** that I am logged into my account
**When** I try to change my password
**Then** I am prevented from creating a password that does not meet security requirements

## Tasks
- [ ] Develop a form for users to change their passwords
- [ ] Include a link to change password in the user profile page
- [ ] Develop a form validation to ensure a suitable password is used
