### ISSUE TITLE
USER STORY: User account Sign in/Sign out

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#13]
As a **user** I can **sign in and sign out of my account** so that **I can keep my account secure and private**

## Acceptance Criteria
- Acceptance Criteria 1:
**Given** that I'm a registered user, who is not logged in
**When** I navigate the sign-in page and enter my credentials correctly
**Then** I am signed into my account

- Acceptance Criteria 2:
**Given** that I'm a registered user, who is currently logged in
**When** I click the sign-out link
**Then** I am signed out of my account

## Tasks
- [x] Develop the ability for users to sign in to their account
- [x] Develop the ability for users to sign out of their account 
- [x] Develop validation to ensure data input is correct

**Comment by Jbachtiger** [comment]
All tasks completed.
