### ISSUE TITLE
USER STORY: Create a blog post

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#18]
As a **user** I can **create a blog post** so that **I can share my ideas and experience**

## Acceptance Criteria
- Acceptance Criteria 1:
**Given** that I am a signed-in user
**When** I navigate to the blog section
**Then** I have the choice to create a new post

- Acceptance Criteria 2:
**Given** that I am a signed-in user and have created a blog post
**When** I save my blog post
**Then** it is available for others to read

## Tasks
- [x] Develop a form to enable a user to submit a blog post
- [x] Develop a way to save the post 
- [x] Develop validation methods

**Comment by Jbachtiger** [comment]
All tasks completed.
