### ISSUE TITLE
USER STORY: Install Django and supporting libraries

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#2]
As a **developer**, I can **set up Django and install all the supporting libraries to get started with the project**, so that **I am ready to start development**

## Tasks
- [x] Install Django
- [x] Install dj_database_url psycopg2
- [x] Install dj3-cloudinary-storage
- [x] Create the Django project
- [x] Create the first app
- [x] Create a requirements.txt file
- [x] Create a Procfile

**Comment by Jbachtiger** [comment]
All tasks completed.
