### ISSUE TITLE
USER STORY: Keep secret keys secure

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#3]
As a **developer**, I can **set up the Django development environment to secure the secrete keys**, so that **I do not expose the secret keys to the public or a party that should not see them**

## Tasks
- [x]  Create an env.py file to store the environment variables needed 
- [x] Amend the Django code to point to the new locations for the secrete keys
- [x] Add the env.py file to the .gitignore file so that it does not get pushed to Github

**Comment by Jbachtiger** [comment]
All tasks completed.
