### ISSUE TITLE
USER STORY: Early deployment of site to Heroku

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#4]
As a **developer**, I can **deploy the site to Heroku**, so that **I can confirm that everything is working before the development of the site and enable continuous testing with the production environment**

## Tasks
- [x] Create a new Heroku app
- [x] Add database to app resources
- [x] Add the secrete keys to config vars in the setting section
- [x] Configure the settings.py file to point at the correct env.py file in development, the os in deployment and adjust the database section to point at the correct database URL from Heroku rather than the local
- [x] Add the Cloudinary API details to env.py file and to the Heroku config vars
- [x] Adjust the settings.py file to point at the relevant Cloundinary libraries

**Comment by Jbachtiger** [comment]
All tasks completed.
