### ISSUE TITLE
USER STORY: Register for an account

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#6]
As a **user** I can **create an account by registering my details** so that **I can comment and like posts**

## Acceptance Criteria
- Acceptance Criteria 1:
**Given** that I am an unregistered user
**When** I am on the homepage
**Then** I can click a button/link which takes me to a registration page

- Acceptance Criteria 2:
**Given** that I am an unregistered user on the user registration page
**When** I enter my email and password and click on the register button
**Then** the system creates me an account and signs me in

## Tasks
- [x] Develop the ability for users to register for an account
- [x] Develop a button/link in the navbar to direct users to the registration page
- [x] Create a user registration form

**Comment by Jbachtiger** [comment]
All tasks completed.
