### ISSUE TITLE
USER STORY: User can edit their profile

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#8]
As a **user** I can **edit my profile** so that **I can keep my information up to date**

## Acceptance Criteria
- Acceptance Criteria 1:
**Given** that I am logged into my profile
**When** I am viewing my profile
**Then** I should be able to edit my details

- Acceptance Criteria 2:
**Given** that I am logged into my profile
**When** I am viewing my profile
**Then** I should be able to edit my details

- Acceptance Criteria 3:
**Given** that I am not logged into my profile
**When** I am viewing my profile page
**Then** I should not be able to edit my details

## Tasks
- [x] Develop the ability for the users to edit their own profiles
- [x] Develop a page where users can edit the information within their profile
- [x] Prevent users from accessing the edit profile page directly when not logged in

**Comment by Jbachtiger** [comment]
All tasks completed.
