### ISSUE TITLE
USER STORY: Users can delete their account

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp4-the-unconventional-programmer#9]
As a **user** I can **delete my account** so that **I can remove my details and posts at my request**

## Acceptance Criteria
- Acceptance Criteria 1:
**Given** that I am a registered user
**When** I access my account
**Then** I have an option to delete it

## Acceptance Criteria
- Acceptance Criteria 2:
**Given** that I am a registered user viewing my account details
**When** I click on the delete option in my profile
**Then** I have to confirm that I want to delete my account and associated data

## Acceptance Criteria
- Acceptance Criteria 3:
**Given** that I am a registered user viewing my account details
**When** I click on the delete option in my profile and confirm this request
**Then** my account and posts/likes I have created are deleted

## Acceptance Criteria
- Acceptance Criteria 4:
**Given** that I am a registered user 
**When** I delete my account
**Then** I get a confirmation of account deletion 

## Tasks
- [ ] Develop a delete button on the user account page
- [ ] Develop a  confirmation request process to confirm deletion requests before the account is deleted
- [ ] Develop a confirmation for the user to show them their account has been deleted
- [ ] When deletion has been requested and confirmed, delete account
